stages:
  data_load:
    cmd: aws s3 cp s3://sign-language-mnist/archive/ data --recursive
    deps:
    - s3://sign-language-mnist/archive/sign_mnist_train/sign_mnist_train.csv
    - s3://sign-language-mnist/archive/sign_mnist_test/sign_mnist_test.csv
    outs:
    - data/sign_mnist_train/sign_mnist_train.csv
    - data/sign_mnist_test/sign_mnist_test.csv

  train:
    cmd: python src/stages/train.py
    deps:
    - data/sign_mnist_train/sign_mnist_train.csv
    - data/sign_mnist_test/sign_mnist_test.csv
    - src/stages/train.py
    outs:
    - models/model.pkl

  evaluate:
    cmd: python src/stages/evaluate.py
    deps:
    - models/model.pkl
    - src/stages/evaluate.py
    - data/sign_mnist_test/sign_mnist_test.csv
    outs:
    - reports/metrics.json