stages:
  data_load:
    cmd: aws s3 cp s3://sign-language-mnist/archive/ data --recursive
    deps:
    - s3://sign-language-mnist/archive/sign_mnist_train/sign_mnist_train.csv
    - s3://sign-language-mnist/archive/sign_mnist_test/sign_mnist_test.csv
    outs:
    - data/sign_mnist_train/sign_mnist_train.csv
    - data/sign_mnist_test/sign_mnist_test.csv

  train:
    cmd: python train.py
    deps:
    - data/processed/sign_mnist_train.csv
    - data/processed/sign_mnist_test.csv
    - train.py
    outs:
    - models/model.pkl

  evaluate:
    cmd: python evaluate.py
    deps:
    - model.h5
    - evaluate.py
    - data/sign_mnist_test/sign_mnist_test.csv
    outs:
    - metrics.json