stages:
  data_load:
    cmd: aws s3 cp s3://sign-language-mnist/archive/ data --recursive
    deps:
    - s3://sign-language-mnist/archive/sign_mnist_train/sign_mnist_train.csv
    - s3://sign-language-mnist/archive/sign_mnist_test/sign_mnist_test.csv
    outs:
    - data/raw/sign_mnist_train/sign_mnist_train.csv
    - data/raw/sign_mnist_test/sign_mnist_test.csv
