base:
  project: "sign language mnist classification"
  random_seed: 42

data_load:
  train_data_path: "data/sign_mnist_train/sign_mnist_train.csv"
  test_data_path: "data/sign_mnist_test/sign_mnist_test.csv"
  target: "label"

model:
  architecture: "resnet34"
  pretrained: true
  save_path: "models/model.pkl"

train:
  num_epochs: 10
  lr: 0.001
  weight_decay: 0.01
  optimizer: Adam
  loss_func: CrossEntropyLoss
  metrics:
    - accuracy
    - f1_score